plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/exec'
    - verifyRelease: |-
        printf "NEXT_VERSION=${nextRelease.version}" >> build.env 
        task build-release version=${nextRelease.version}
  - - '@semantic-release/github'
    - assets:
        - 'docs/api-spec/*'
        - 'src/target/gym-api-*.jar'
branches:
  - 'main'
