plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/exec'
    - verifyRelease: './src/mvnw versions:set -DnewVersion="${nextRelease.version}" && echo "NEXT_VERSION=${nextRelease.version}" >> build.env'
  - '@semantic-release/github'
  - - '@semantic-release/git'
    - assets:
        - pom.xml
      message: 'chore(release): bump ${nextRelease.version}'

branches:
  - 'main'
