# https://taskfile.dev

version: '3'

vars:
  DOCS_DIR: ./docs
  DOCKER_COMPOSE_FILE: src/docker/docker-compose.yaml

tasks:
  default:
    cmds:
      - task --list-all
    silent: true
  docs:
    desc: generate docs
    cmds:
      - plantuml model.puml -tsvg
    dir: '{{.DOCS_DIR}}'
  dev:
    desc: run devleopment setup, starts containers needed for development
    cmds:
      - docker-compose -f {{.DOCKER_COMPOSE_FILE}} up
    preconditions:
      - which docker-compose
      - test -f
