# https://taskfile.dev

version: '3'

vars:
  DOCS_DIR: '{{.ROOT_DIR}}/docs'
  API_SPEC_DIR: '{{.DOCS_DIR}}/api-spec'
  DOCKER_COMPOSE_FILE: '{{.ROOT_DIR}}/src/docker/docker-compose.yaml'
  JAVA_ROOT: '{{.ROOT_DIR}}/src'
tasks:
  default:
    cmds:
      - task --list-all
    silent: true
  docs:
    desc: generate docs
    cmds:
      - plantuml model.puml -tsvg
    dir: '{{.DOCS_DIR}}'
  dev:
    desc: run devleopment setup, starts containers needed for development
    cmds:
      - docker-compose -f {{.DOCKER_COMPOSE_FILE}} up
    preconditions:
      - which docker-compose
      - test -f {{.DOCKER_COMPOSE_FILE}}
  api-spec:
    desc: generate openAPI spec
    dir: '{{.JAVA_ROOT}}'
    cmds:
      - mkdir -p {{.API_SPEC_DIR}}/apispec
      - ./mvnw test -Dtest=OpenApiSpecGeneratorTest -Dspring.profiles.active=test
      - cp target/openapi.{json,yaml} {{.API_SPEC_DIR}}
    preconditions:
      - test -f mvnw
      - test -d "$(dirname {{.DOCS_DIR}})" # parent dir of apispec exists
  test:
    desc: Run tests
    dir: '{{.JAVA_ROOT}}'
    cmds:
      - ./mvnw test -Dtest=!OpenApiSpecGeneratorTest -Dspring.profiles.active=test
    preconditions:
      - test -f mvnw
  set-version:
    desc: Set version [version=required]
    cmds:
      - cd '{{.JAVA_ROOT}}' && ./mvnw versions:set -DnewVersion={{.version}} && ./mvnw versions:commit
    requires:
      vars:
        - version
