openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost
  description: Generated server url
paths:
  /exercises:
    get:
      tags:
      - exercise-controller
      operationId: listCategories
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ExerciseDto"
components:
  schemas:
    ExerciseDto:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        name:
          type: string
        targetMuscles:
          type: array
          items:
            $ref: "#/components/schemas/TargetMuscleDto"
          uniqueItems: true
    TargetMuscleDto:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        name:
          type: string
