services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 8081:8080
    command:
      # # exporting 
      # - export
      # - --realm
      # - gym
      # - --users
      # - same_file
      # - --file
      # - /opt/keycloak/data/import/gym.json

      - start
      - --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: true
      KC_DB: postgres
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_DB_URL: jdbc:postgresql://keycloak-db/postgres
      KC_DB_PASSWORD: admin
      KC_DB_USERNAME: postgres
    volumes:
      - ./keycloak/:/opt/keycloak/data/import
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - keycloak-db
    networks: 
      - keycloak_network

  keycloak-db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak_network


  gym-api-db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: &dbpass supersecretpassword
      POSTGRES_USER: &dbuser gymapi-user
      POSTGRES_DB: &dbname gymapi
    ports:  
      - 5432:5432
  
      # FIXME fix
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    environment:
      ADMINER_DEFAULT_DB_NAME: *dbname
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_SERVER: gym-api-db
      

volumes:
  postgres_data:
    driver: local

networks:
  keycloak_network:
    driver: bridge
