services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 8081:8080
    command:
      # - export
      # - --realm
      # - gym
      # - --users
      # - same_file
      # - --dir
      # - /opt/keycloak/data/import

      - start
      - --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: true
      KC_DB: postgres
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_DB_URL: jdbc:postgresql://keycloak-db/postgres
      KC_DB_PASSWORD: admin
      KC_DB_USERNAME: postgres
    volumes:
      - ./keycloak/:/opt/keycloak/data/import
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - keycloak-db
    networks:
      - keycloak_network

  keycloak-db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak_network


  gym-api-db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: gym-api-user
      POSTGRES_DB: &dbname gym-api
    ports:
      - 5432:5432
    container_name:
      &dbserver gym-api-db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    environment:
      ADMINER_DEFAULT_DB_NAME: *dbname
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_SERVER: *dbserver

  stripe-cli:
    image: stripe/stripe-cli:latest
    environment:
      STRIPE_API_KEY: ${STRIPE_API_KEY}
    command: listen --forward-to=http://host.docker.internal:8080/stripe/webhook


volumes:
  postgres_data:
    driver: local

networks:
  keycloak_network:
    driver: bridge
