@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class exercise {
   name: varchar(255)
   uuid: uuid
}
class exercise_target_muscle {
   exercise_uuid: uuid
   target_muscle_uuid: uuid
}
class hall {
   hall_type_uuid: uuid
   hall_description: varchar(255)
   hall_name: varchar(255)
   uuid: uuid
}
class hall_type {
   name: varchar(255)
   uuid: uuid
}
class maintenance_task {
   planned_end_date: timestamp(6)
   planned_start_date: timestamp(6)
   maintainer_uuid: uuid
   maintenance_hall_uuid: uuid
   description: varchar(255)
   uuid: uuid
}
class membership {
   valid_from: timestamp(6)
   valid_until: timestamp(6)
   membership_type_uuid: uuid
   uuid: uuid
}
class membership_type {
   currency: varchar(3)
   price: numeric(38,2)
   type: varchar(255)
   uuid: uuid
}
class payment {
   currency: varchar(3)
   price: numeric(38,2)
   external_ref_id: uuid
   external_ref_type: varchar(255)
   status: varchar(255)
   payment_id: uuid
}
class target_muscle {
   name: varchar(255)
   uuid: uuid
}
class user_account_connection {
   user_uuid: uuid
   external_authorization_provider_name: varchar(255)
   external_authorization_user_id: varchar(255)
   uuid: uuid
}
class user_role {
   role_name: varchar(255)
   uuid: uuid
}
class users {
   date_of_birth: timestamp(6)
   membership_uuid: uuid
   email: varchar(255)
   first_name: varchar(255)
   image_url: varchar(255)
   last_name: varchar(255)
   phone_number: varchar(255)
   username: varchar(255)
   uuid: uuid
}
class users_roles {
   roles_uuid: uuid
   user_uuid: uuid
}
class workout_session {
   date: date
   coach_uuid: uuid
   hall_uuid: uuid
   description: varchar(255)
   title: varchar(255)
   uuid: uuid
}
class workout_session_attendants {
   attendants_uuid: uuid
   workout_session_uuid: uuid
}
class workout_session_exercise {
   exercise_order: integer
   reps: integer
   weight: real
   exercise_uuid: uuid
   workout_session_uuid: uuid
   uuid: uuid
}

exercise_target_muscle      -[#595959,plain]-^  exercise                   : "exercise_uuid:uuid"
exercise_target_muscle      -[#595959,plain]-^  target_muscle              : "target_muscle_uuid:uuid"
hall                        -[#595959,plain]-^  hall_type                  : "hall_type_uuid:uuid"
maintenance_task            -[#595959,plain]-^  hall                       : "maintenance_hall_uuid:uuid"
maintenance_task            -[#595959,plain]-^  users                      : "maintainer_uuid:uuid"
membership                  -[#595959,plain]-^  membership_type            : "membership_type_uuid:uuid"
user_account_connection     -[#595959,plain]-^  users                      : "user_uuid:uuid"
users                       -[#595959,plain]-^  membership                 : "membership_uuid:uuid"
users_roles                 -[#595959,plain]-^  user_role                  : "roles_uuid:uuid"
users_roles                 -[#595959,plain]-^  users                      : "user_uuid:uuid"
workout_session             -[#595959,plain]-^  hall                       : "hall_uuid:uuid"
workout_session             -[#595959,plain]-^  users                      : "coach_uuid:uuid"
workout_session_attendants  -[#595959,plain]-^  users                      : "attendants_uuid:uuid"
workout_session_attendants  -[#595959,plain]-^  workout_session            : "workout_session_uuid:uuid"
workout_session_exercise    -[#595959,plain]-^  exercise                   : "exercise_uuid:uuid"
workout_session_exercise    -[#595959,plain]-^  workout_session            : "workout_session_uuid:uuid"
@enduml
