spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gym-api
    username: gym-api-user
    password: admin
    driver-class-name: org.postgresql.Driver
  application:
    name: gym-api
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/gym/.well-known/openid-configuration


springdoc:
  api-docs:
    path: '/api-docs'
  swagger-ui:
    path: '/swagger'
