spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gym-api
    username: gym-api-user
    password: admin
    driver-class-name: org.postgresql.Driver
  application:
    name: gym-api
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create
server:
  servlet:
    context-path: /api
springdoc:
  api-docs:
    path: '/api-docs'
  swagger-ui:
    path: '/swagger'
