name: Semantic Release

on:
  workflow_run:
    workflows:
      - tests
    types:
      - completed
    branches:
      - main

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: nicknovitski/nix-develop@v1
      - run: task semrel-ci

permissions:
  contents: write
